import { Product } from "../models/product.model";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Green Jhumka",
    price: 250,
    image: "/images/img4.png",
    altText: "Green jhumka earrings",
    category: "hooks",
    isNew: true,
    isWishlisted: false,
  },
  {
    id: 2,
    name: "Lotus Jhumka",
    price: 250,
    image: "/images/img3.jpeg",
    altText: "Lotus design jhumka earrings",
    category: "hooks",
    isNew: true,
    isWishlisted: false,
  },
  {
    id: 3,
    name: "Golden Pearl Jhumka",
    price: 299,
    image: "/images/img5.png",
    altText: "Golden pearl jhumka earrings",
    category: "hooks",
    isNew: true,
    isWishlisted: false,
  },
  {
    id: 4,
    name: "Pink Stone Jhumka",
    price: 275,
    image: "/images/img5.png",
    altText: "Pink stone jhumka earrings",
    category: "hooks",
    isNew: true,
    isWishlisted: false,
  },
  {
    id: 5,
    name: "Traditional Gold Jhumka",
    price: 350,
    image: "/images/bracelet.png",
    altText: "Traditional gold jhumka earrings",
    category: "hooks",
    isNew: true,
    isWishlisted: false,
  },
  {
    id: 6,
    name: "Blue Beaded Jhumka",
    price: 225,
    image: "/images/leaves.png",
    altText: "Blue beaded jhumka earrings",
    category: "hooks",
    isNew: false,
    isWishlisted: false,
  },
  {
    id: 7,
    name: "Red Floral Jhumka",
    price: 280,
    image: "/images/logo.png",
    altText: "Red floral jhumka earrings",
    category: "hooks",
    isNew: false,
    isWishlisted: false,
  },
  {
    id: 8,
    name: "Pearl Drop Jhumka",
    price: 320,
    image: "/images/nature.png",
    altText: "Pearl drop jhumka earrings",
    category: "hooks",
    isNew: false,
    isWishlisted: false,
  },
  {
    id: 9,
    name: "Silver Oxidized Jhumka",
    price: 199,
    image: "/images/natureA.png",
    altText: "Silver oxidized jhumka earrings",
    category: "hooks",
    isNew: false,
    isWishlisted: false,
  },
  {
    id: 10,
    name: "White Stone Jhumka",
    price: 260,
    image: "/images/natureB.png",
    altText: "White stone jhumka earrings",
    category: "hooks",
    isNew: false,
    isWishlisted: false,
  },
];